---
title: Zero inflated models
output:
  xaringan::moon_reader:
    css: "lab-slides.css"
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
editor_options: 
  chunk_output_type: console
---

### Agenda

.large[
* Final exam on May 3, 2pm
  * 3 hours, in person, closed notes, bring calculator
  * Cumulative, divided roughly evenly between topics
  * Friday: review day for final
  * Final exam practice questions, and solutions, on course website
* Today: 
  * wrap up zero inflated Poisson (ZIP) models
  * Some work time on Lab 9 and exam review questions
  * Course evaluations
]

---

### Data: College drinking

.large[
Survey data from 77 college students on a dry campus (i.e., alcohol is prohibited) in the US. Survey asks students "How many alcoholic drinks did you consume last weekend?"

* `drinks`: the number of drinks the student reports consuming
* `sex`: an indicator for whether the student identifies as male
* `OffCampus`: an indicator for whether the student lives off campus
* `FirstYear`: an indicator for whether the student is a first-year student

.question[
Our goal: model the number of drinks students report consuming.
]
]

---

### Excess zeros

.large[
The problem:

* There are two groups of people contributing 0s to the data: those who never drink, and those who sometimes drink but didn't drink last weekend
* By itself, a Poisson distribution doesn't do a good job modeling data that is a mixture of these two groups
* We don't know which students never drink

Plan: create separate models for drinkers and non-drinkers, then combine into one model that we can fit with the observed data.
]

---

### Zero-inflated Poisson (ZIP) model

.large[
$$P(Y_i = y) = \begin{cases} e^{-\lambda_i}(1 - \alpha_i) + \alpha_i & y = 0 \\ \dfrac{e^{-\lambda_i} \lambda_i^y}{y!}(1 - \alpha_i) & y > 0 \end{cases}$$

where

$\log \left( \dfrac{\alpha_i}{1 - \alpha_i} \right) = \gamma_0 + \gamma_1 FirstYear_i$

$\log(\lambda_i) = \beta_0 + \beta_1 OffCampus_i + \beta_2 Male_i$

* $\alpha_i =$ probability the student doesn't drink
* $\lambda_i =$ average number of drinks if the student *does* drink
]

---

### The fitted model

.large[
$$P(Y_i = y) = \begin{cases} e^{-\lambda_i}(1 - \alpha_i) + \alpha_i & y = 0 \\ \dfrac{e^{-\lambda_i} \lambda_i^y}{y!}(1 - \alpha_i) & y > 0 \end{cases}$$

$\log \left( \dfrac{\widehat{\alpha}_i}{1 - \widehat{\alpha}_i} \right) = -0.60 + 1.14 FirstYear_i$

$\log(\widehat{\lambda}_i) = 0.75 + 0.42 \ OffCampus_i + 1.02 \ Male_i$

.question[

What is the estimated average number of drinks for a male student who lives off campus and sometimes drinks?

Work with a partner to answer this question, then we will discuss as a group.

]
]

---

### The fitted model

.large[
$$P(Y_i = y) = \begin{cases} e^{-\lambda_i}(1 - \alpha_i) + \alpha_i & y = 0 \\ \dfrac{e^{-\lambda_i} \lambda_i^y}{y!}(1 - \alpha_i) & y > 0 \end{cases}$$

$\log \left( \dfrac{\widehat{\alpha}_i}{1 - \widehat{\alpha}_i} \right) = -0.60 + 1.14 FirstYear_i$

$\log(\widehat{\lambda}_i) = 0.75 + 0.42 \ OffCampus_i + 1.02 \ Male_i$

Here $\lambda_i$ is the average number of drinks for a student who sometimes drinks. For a male student who lives off campus:

$\widehat{\lambda}_i = \exp\{0.75 + 0.42 + 1.02\} = 8.93$
]

---

### The fitted model

.large[
$$P(Y_i = y) = \begin{cases} e^{-\lambda_i}(1 - \alpha_i) + \alpha_i & y = 0 \\ \dfrac{e^{-\lambda_i} \lambda_i^y}{y!}(1 - \alpha_i) & y > 0 \end{cases}$$

$\log \left( \dfrac{\widehat{\alpha}_i}{1 - \widehat{\alpha}_i} \right) = -0.60 + 1.14 FirstYear_i$

$\log(\widehat{\lambda}_i) = 0.75 + 0.42 \ OffCampus_i + 1.02 \ Male_i$

.question[

What is the estimated probability that a male first year student who lives off campus had at least one drink last weekend?

Work with a partner to answer this question, then we will discuss as a group.

]
]

---

### The fitted model

.large[
$$P(Y_i = y) = \begin{cases} e^{-\lambda_i}(1 - \alpha_i) + \alpha_i & y = 0 \\ \dfrac{e^{-\lambda_i} \lambda_i^y}{y!}(1 - \alpha_i) & y > 0 \end{cases}$$

$\log \left( \dfrac{\widehat{\alpha}_i}{1 - \widehat{\alpha}_i} \right) = -0.60 + 1.14 FirstYear_i$

$\log(\widehat{\lambda}_i) = 0.75 + 0.42 \ OffCampus_i + 1.02 \ Male_i$

For a male first year student:

* $\widehat{\alpha}_i = 0.63$ and $\widehat{\lambda}_i = 8.93$

$\widehat{P}(Y_i > 0) = 1 - \widehat{P}(Y_i = 0) = 1 - (e^{-\widehat{\lambda}_i}(1 - \widehat{\alpha}_i) + \widehat{\alpha}_i)  \\ \hspace{2cm} = 1 - (e^{-8.93}(1 - 0.63) + 0.63) = 0.37$
]

